#!/bin/bash

# 使用 `envsubst` 将模板文件中的 ${NGINX_PORT} 替换为实际的环境变量值
envsubst '${NGINX_PORT}${API_PORT}' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf
# 启动前端nginx服务
nginx
# 启动后端 API 服务（src/main.py 已不存在，使用 main_api.py）
export PYTHONPATH=${PYTHONPATH}:. && python src/main_api.py

